# Generated by Django 2.2.5 on 2020-06-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerlogin',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
