# Generated by Django 2.2.5 on 2020-06-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20200614_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerlogin',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
